### ISSUE TITLE
Wiktionary support?

### ISSUE THREAD

**Issue by hermeneuticlens** [soumyaDghosh/wike-snap#1]
Absolutely love this app! But would appreciate a Wiktionary mode. That way you will make arguably the best dictionary/thesaurus app, and I don't have to use GoldenDict anymore!

**Comment by soumyaDghosh** [comment]
Hi, thanks a lot for your support. This snap is maintained by me, but the app itself is developed by @hugolabe I have created an issue in the main repo. In the mean time, if you like this snap and if you want to, please consider supporting me. Thanks a lot! Have a great day.

**Comment by hermeneuticlens** [comment]
Thank you!
